import Head from 'next/head'
import React, { Children,useEffect } from 'react'
import Mobile_Tabs from './Mobile_Tabs'
import SideBar from './SideBar'
import TopBar from './TopBar'

const Layout = ({children ,title}) => {
  
 

  return (
    <>
      <Head >
        <title>{title? title+ '-PMI Report Management System':'PMI Report Management System'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon123.ico" />
        <script src="https://code.jquery.com/jquery-3.6.3.js"></script>
      </Head>
     
    <div>
        <div className='container_main'>
        <div className='side_bar'>
       <SideBar></SideBar>
       </div>
       <main className='right_side_section'>
        <div className='top_bar'>
          <TopBar></TopBar>
        </div>
        <div className='page_container'>
           {children}
        </div>
       </main>
       <Mobile_Tabs/>
        </div>
       
    </div>
    </>
  )
}

export default Layout