import Head from 'next/head'
import React, { useEffect, useState} from 'react'
import Mobile_Tabs from './Mobile_Tabs'
import SideBar from './SideBar'
import TopBar from './TopBar'
import Router from 'next/router'
import { LoadingOutlined } from '@ant-design/icons';
import { Spin } from 'antd';
import { useRouter } from "next/router";

const Layout = ({children ,title}) => {
  const router = useRouter()

  const[routeLoad,setRouteLoad]=useState(false)
  
  Router.events.on('routeChangeStart',(url)=>{

    setRouteLoad(true)

   
  })
  const antIcon = (
    <LoadingOutlined
      style={{
        fontSize: 58,
      }}
      spin
    />
  );
  Router.events.on('routeChangeComplete',(url)=>{
  
    setRouteLoad(false)

  })

useEffect(()=>{
localStorage.setItem("ApiEndPoint",process.env.API_ENDPOINT)
},[])

  return (
    <>
      <Head >
        <title>{title? title+ '-PMI Report Management System':'PMI Report Management System'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon123.ico" />
        <script src="https://code.jquery.com/jquery-3.6.3.js"></script>
        {/* <link rel="preload"></link>
        <link rel="prefetch"></link> */}
      </Head>
     
    <div>
        <div className='container_main'>
        <div className='side_bar'>
       <SideBar></SideBar>
       </div>
       <main className='right_side_section'>
        <div className='top_bar'>
          <TopBar></TopBar>
        </div>
        <div className='page_container'>


          {routeLoad?
           <div className='loaderroute'>
           <Spin indicator={antIcon} /></div>:
           children}
        </div>
       </main>
       
       <Mobile_Tabs  />
        </div>
       
    </div>
    </>
  )
}

export default Layout